"""initial postgres schema

Revision ID: b6ba7576999d
Revises: 
Create Date: 2026-05-28 19:28:37.111193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6ba7576999d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uix_user_email'),
    sa.UniqueConstraint('username', name='uix_user_username')
    )
    op.create_table('deck',
    sa.Column('deck_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(length=255), nullable=False),
    sa.Column('deck_description', sa.Text(), server_default='', nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deck_id'),
    sa.UniqueConstraint('user_id', 'deck_name', name='uix_user_deck_name')
    )
    op.create_index('idx_one_default_deck_per_user', 'deck', ['user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_index('idx_user_id', 'deck', ['user_id'], unique=False)
    op.create_table('note',
    sa.Column('note_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_type_id', sa.Integer(), nullable=False),
    sa.Column('fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('sort_field', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('hint', sa.String(length=255), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id'),
    sa.UniqueConstraint('user_id', 'note_type_id', 'checksum', name='uix_user_note_type_checksum')
    )
    op.create_index('idx_note_user_checksum', 'note', ['user_id', 'note_type_id', 'checksum'], unique=False)
    op.create_index('idx_note_user_id', 'note', ['user_id', 'note_id'], unique=False)
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('template_ord', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('due', sa.Date(), nullable=False),
    sa.Column('interval', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ease', sa.Float(), server_default='2.5', nullable=False),
    sa.Column('reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('new', 'learning', 'review', 'relearning')", name='ck_card_status'),
    sa.CheckConstraint('ease > 0', name='ck_card_ease_positive'),
    sa.CheckConstraint('interval >= 0', name='ck_card_interval_non_negative'),
    sa.CheckConstraint('lapses >= 0', name='ck_card_lapses_non_negative'),
    sa.CheckConstraint('reps >= 0', name='ck_card_reps_non_negative'),
    sa.CheckConstraint('template_ord >= 0', name='ck_card_template_ord_non_negative'),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['note.note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('user_id', 'note_id', 'template_ord', name='uix_user_note_template_ord')
    )
    op.create_index('idx_card_status_due', 'card', ['user_id', 'status', 'due'], unique=False)
    op.create_index('idx_card_user_deck_due', 'card', ['user_id', 'deck_id', 'due'], unique=False)
    op.create_index('idx_card_user_note', 'card', ['user_id', 'note_id'], unique=False)
    op.create_table('review_log',
    sa.Column('review_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=30), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=False),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('old_due', sa.Date(), nullable=True),
    sa.Column('new_due', sa.Date(), nullable=True),
    sa.Column('old_interval', sa.Integer(), nullable=False),
    sa.Column('new_interval', sa.Integer(), nullable=False),
    sa.Column('old_ease', sa.Float(), nullable=False),
    sa.Column('new_ease', sa.Float(), nullable=False),
    sa.Column('old_lapses', sa.Integer(), nullable=False),
    sa.Column('new_lapses', sa.Integer(), nullable=False),
    sa.Column('old_reps', sa.Integer(), nullable=False),
    sa.Column('new_reps', sa.Integer(), nullable=False),
    sa.Column('old_step_index', sa.Integer(), nullable=True),
    sa.Column('new_step_index', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('review_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("new_status IN ('new', 'learning', 'review', 'relearning')", name='ck_review_log_new_status'),
    sa.CheckConstraint("old_status IN ('new', 'learning', 'review', 'relearning')", name='ck_review_log_old_status'),
    sa.CheckConstraint("rating IN ('good', 'again')", name='ck_review_log_rating'),
    sa.CheckConstraint('new_ease > 0', name='ck_review_log_new_ease_positive'),
    sa.CheckConstraint('new_interval >= 0', name='ck_review_log_new_interval_non_negative'),
    sa.CheckConstraint('new_lapses >= 0', name='ck_review_log_new_lapses_non_negative'),
    sa.CheckConstraint('new_reps >= 0', name='ck_review_log_new_reps_non_negative'),
    sa.CheckConstraint('old_ease > 0', name='ck_review_log_old_ease_positive'),
    sa.CheckConstraint('old_interval >= 0', name='ck_review_log_old_interval_non_negative'),
    sa.CheckConstraint('old_lapses >= 0', name='ck_review_log_old_lapses_non_negative'),
    sa.CheckConstraint('old_reps >= 0', name='ck_review_log_old_reps_non_negative'),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_id'], ['note.note_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_log_id')
    )
    op.create_index('idx_review_log_card_time', 'review_log', ['user_id', 'card_id'], unique=False)
    op.create_index('idx_review_log_deck_time', 'review_log', ['user_id', 'deck_id', 'review_time'], unique=False)
    op.create_index('idx_review_log_user_time', 'review_log', ['user_id', 'review_time'], unique=False)
    op.create_table('study_session',
    sa.Column('study_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('current_card_id', sa.Integer(), nullable=True),
    sa.Column('current_hint_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_back_revealed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('learning_queue', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('review_queue', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('new_queue', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('today', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status = 'active'", name='ck_study_session_status'),
    sa.ForeignKeyConstraint(['current_card_id'], ['card.card_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.deck_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_session_id'),
    sa.UniqueConstraint('session_id', name='uix_study_session_session_id')
    )
    op.create_index('idx_study_session_user_deck_today', 'study_session', ['user_id', 'deck_id', 'today'], unique=False)
    op.create_index('idx_study_session_user_id', 'study_session', ['user_id'], unique=False)
    op.create_index('idx_study_session_user_session_id', 'study_session', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_study_session_user_session_id', table_name='study_session')
    op.drop_index('idx_study_session_user_id', table_name='study_session')
    op.drop_index('idx_study_session_user_deck_today', table_name='study_session')
    op.drop_table('study_session')
    op.drop_index('idx_review_log_user_time', table_name='review_log')
    op.drop_index('idx_review_log_deck_time', table_name='review_log')
    op.drop_index('idx_review_log_card_time', table_name='review_log')
    op.drop_table('review_log')
    op.drop_index('idx_card_user_note', table_name='card')
    op.drop_index('idx_card_user_deck_due', table_name='card')
    op.drop_index('idx_card_status_due', table_name='card')
    op.drop_table('card')
    op.drop_index('idx_note_user_id', table_name='note')
    op.drop_index('idx_note_user_checksum', table_name='note')
    op.drop_table('note')
    op.drop_index('idx_user_id', table_name='deck')
    op.drop_index('idx_one_default_deck_per_user', table_name='deck', postgresql_where=sa.text('is_default = true'))
    op.drop_table('deck')
    op.drop_table('user')
    # ### end Alembic commands ###
