from contextlib import nullcontext
from ..scheduler.simple_scheduler import Scheduler_v1 as scheduler
from .review import ReviewLog


class ReviewLoggerService:
    '''
    handle review logger related operations

    operations:
    read card, normalize card data, add review log, 
    ask scheduler for next review time,update card data
    '''
    def __init__(self, card_repo,review_repo,scheduler:scheduler,transaction_manager=None):
        self.__card_repo=card_repo
        self.__review_repo=review_repo
        self.__scheduler=scheduler
        self.__transaction_manager=transaction_manager

    def __transaction(self):
        # used to manage the transaction
        if self.__transaction_manager is None:
            return nullcontext()
        return self.__transaction_manager.transaction()

    # Read card → normalize rating → call scheduler → update card → write revlog
    def review_card(self, user_id:int, card_id: int, rating:str,today=None,hint_used:bool=False):
        normalized_rating=self.__normalize_rating(rating)
        with self.__transaction():
            card=self.__card_repo.get_card(user_id, card_id)
            if card is None:
                raise ValueError(f"Card with id {card_id} not found")
            
            # save old status
            old_status=card.status
            old_due=card.due
            old_interval=card.interval
            old_ease=card.ease
            old_lapses=card.lapses
            old_reps=card.reps
            old_step_index=card.step_index
            # scheduler calculates the next review time
            result = self.__scheduler.schedule(card,normalized_rating,today=today,review_context={'hint_used':hint_used})

            # apply scheduler result to card
            card.status=result["status"]
            card.due=result["due"]
            card.interval=result["interval"]
            card.ease=result["ease"]
            card.lapses=result["lapses"]
            card.reps=result["reps"]
            card.step_index=result["step_index"]
            # review time?
            card.touch()

            updated_card=self.__card_repo.update_card(user_id, card)

            log=ReviewLog(
                user_id=user_id,
                note_id=updated_card.note_id,
                card_id=updated_card.card_id,
                deck_id=updated_card.deck_id,
                rating=normalized_rating,
                old_status=old_status,
                new_status=updated_card.status,
                old_due=old_due,
                new_due=updated_card.due,
                old_interval=old_interval,
                new_interval=updated_card.interval,
                old_ease=old_ease,
                new_ease=updated_card.ease,
                old_lapses=old_lapses,
                new_lapses=updated_card.lapses,
                old_reps=old_reps,
                new_reps=updated_card.reps,
                old_step_index=old_step_index,
                new_step_index=updated_card.step_index,
                # review_time automatically generated by database
                hint_used=hint_used,
            )
            saved_log=self.__review_repo.add_log(user_id, log)

        return {'log':saved_log ,'card':updated_card}

    # Get all review logs history by card id
    def get_review_logs_history(self, user_id:int, card_id: int):
        return self.__review_repo.get_logs_by_card_id(user_id, card_id)
    
    def get_all_review_logs_history(self, user_id:int):
        return self.__review_repo.get_all_logs_by_user_id(user_id)
        
    # Normalize user input rating to a standardized format
    def __normalize_rating(self, rating:str) -> str:
        '''
        map user input to v1 rating set

        rating:
        good
        again
        unknown/forget->again
        '''
        if not isinstance(rating, str):
            raise ValueError("Rating must be a string")
        value=rating.strip().lower() # 处理空格和大小写
        aliases={
            "good": "good",
            "again": "again",
            "unknown": "again",
            "forget": "again",
        }

        if aliases.get(value) is None:
            raise ValueError(f"Unsupported rating{value}")

        return aliases.get(value)